<?php
/*
Plugin:      Poll
Version:     0.1
Author:      Samuel Abels
Description: Adds support for pollings.
Constructor: poll_init
Active:      0
*/
include_once 'plugins/poll/poll.class.php'; //FIXME: hardcoded path.
include_once 'plugins/poll/poll_printer.class.php'; //FIXME: hardcoded path.


function poll_init($forum) {
  $user = $forum->get_current_user();
  if ($user->is_anonymous())
    return;

  // Add a link to the poll button in the index bar.
  $poll_url = new URL('?', cfg('urlvars'), lang('poll'));
  $poll_url->set_var('action', 'poll_add');
  $forum->add_extra_indexbar_link($poll_url);

  // Register our extra actions.
  $forum->register_action('poll_add',    'poll_on_add');
  $forum->register_action('poll_submit', 'poll_on_submit');
  $forum->register_action('poll_show',   'poll_on_show');
}


function poll_on_add($forum) {
  $printer = new PollPrinter($forum);
  $printer->show_form(new Poll());
}


function poll_on_show($forum) {
  echo "poll_on_show() called.";
  //FIXME: fetch the poll from the database.
  $printer = new PollPrinter($forum);
  $printer->show_poll($poll);
}


function poll_on_submit($forum) {
  $printer = new PollPrinter($forum);
  $poll    = _poll_get_from_post();

  // Add a new option to the poll form.
  if ($_POST['add_row']) {
    $poll->add_option('');
    return $printer->show_form($poll);
  }

  // Create the new poll.
  elseif ($_POST['send']) {
    // Sanity check.
    $err = $poll->check();
    if ($err)
      return $printer->show_form($poll, $err);

    // Save the poll.
    $poll_id = _save_poll($forum, $poll);
    if (!$poll_id)
      return $printer->show_form($poll, lang('poll_save_failed'));

    // Refer to the poll.
    $poll_url = new URL('?', cfg('urlvars'), lang('poll'));
    $poll_url->set_var('action', 'poll_show');
    $poll_url->set_var('id',     $poll_id);
    $forum->_refer_to($poll_url->get_string());
  }
}


/***********************************************
 * Utilities.
 ***********************************************/
function _poll_get_from_post() {
  $n_options = (int)$_POST['n_options'];
  $poll      = new Poll($_POST['poll_title']);
  $poll->set_allow_multiple($_POST['allow_multiple'] == 'on');
  for ($i = 0; $i < $n_options; $i++)
    $poll->add_option($_POST["poll_option$i"]);
  return $poll;
}


function _save_poll($forum, $poll) {
  $forum_id = $forum->get_current_forum_id();
  $user     = $forum->get_current_user();
  $group    = $forum->get_current_group();

  // Map the poll into a message.
  $message = new Message;
  $message->set_renderer('poll');
  $message->set_from_user($user);
  $message->set_from_group($group);
  $message->set_subject($poll->get_title());
  $message->set_body('generated by the poll plugin');

  //FIXME: save a poll that references the message.

  $forum->_get_forumdb()->insert($forum_id, NULL, $message);
  return $message->get_id();
}
?>
